name: analisador_texto
description: Aplicativo Analisador de Texto com Autenticação
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # Formulários e Validação
  flutter_masked_text2: ^2.0.0
  mask_text_input_formatter: ^2.5.0
  validadores: ^2.0.2
  
  # Gerenciamento de Estado
  provider: ^6.1.1
  
  # Banco de Dados
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Segurança
  crypto: ^3.0.3
  
  # Utilitários
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/